// Generated by CoffeeScript 1.3.3
(function() {

  Ext.define("Locale.controller.Help", {
    extend: "Ext.app.Controller",
    config: {
      control: {
        selectfield: {
          change: "onHelpClick"
        }
      }
    },
    onHelpClick: function(message) {
      return alert('helllooooo');
    },
    onAboutClick: function() {
      return alert('about click');
    }
  });

}).call(this);
