// Generated by CoffeeScript 1.3.3
(function() {

  Ext.define("Locale.controller.Main", {
    extend: "Ext.app.Controller",
    config: {
      control: {
        selectfield: {
          change: "onLocalePick"
        }
      }
    },
    onLocalePick: function(field, value) {
      var rec, store;
      if (value.length > 2) {
        store = field.getStore();
        rec = store.findRecord("text", value);
        value = rec.get(field.getValueField());
      }
      return Ux.locale.Manager.updateLocale(value);
    }
  });

}).call(this);
